### ISSUE TITLE
Values of nan in pixmap not properly interpreted

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzle#10]
This code relies on the input pixmap to define where the input pixels should be placed in the output frame.  However, some input images have regions (at the edges) which are not defined and have values of 'nan' in the input image.  This results in output positions of 'nan' in the pixmap since the input pixels are not intended to be mapped to any output pixel.  Unfortunately, the pixmap values for each row are used to set the limits for many of the loops used to drizzle the input pixels to the output frame and values of 'nan' cause drizzle to completely skip all the data in those rows.  

The drizzle code should have some logic integrated into it to ignore values of 'nan' as returned by the pixmap array.  The code should also treat those pixels as 'skipped' in the algorithm.  

The available workaround is to insure that the input pixmap does NOT contain any 'nan' values so that the current drizzle code does not get confused and skip over all the input data.

**Comment by bernie-simon** [comment]
There were several iterations of this fix, but pixmap NaN problem was fixed with the June 21st commit.
