### ISSUE TITLE
How to incorporate masking when drizzling?

### ISSUE THREAD

**Issue by joaquinhernandezg** [spacetelescope/drizzle#105]
Hi, how can masking be incorporated when drizzling a set of images? I am using drizzle to do templates for difference imaging from ground-based images, as it simplifies a lot of steps, but I do not know how to appropriately incorporate masking of cosmic rays and detector artifacts. I was thinking on just drizzle each individual exposure and then mask and average, but probably there is a more straightforward way to do it.

**Comment by mcara** [comment]
If you do have a mask identifying "bad" pixels (cosmic rays, etc.) you could provide it as input to the `Drizzle.add_image` or `Drizzle.add_fits_file` functions - see parameter `inwht`, e.g., https://github.com/spacetelescope/drizzle/blob/a2665bf56108778cc49fdd0657a71a84597a7c0b/drizzle/drizzle.py#L276C39-L278

NOTE: `inwht` must be an `numpy.int32` array.
