### ISSUE TITLE
Sgmentation violation when pixmap is mostly NaNs

### ISSUE THREAD

**Issue by bernie-simon** [spacetelescope/drizzle#21]
Drizzle is throwing a segmentation violation when it interpolates a position in a pixmap that is mostly NaNs. This will happen when handling JWST spectra, as the region outside the spectra is all NaNs. The problem is that the current code blows up when asked to interpolate in a line that is entirely NaNs. The solution is to rewrite the code in shrink_segment so that it "thinks" in two dimensions at a time instead of only one. Line handling then becomes a degenerate case where the second dimension has length one. The other half of the fix is to do a better job of error handling so that when the bound for the interpolated point cannot be found, the point is skipped. 

After viewing the code, I saw a few other issues. It shouldn't try so hard to find a bound by searching the entire line, it should give up after a certain range of pixels. This will speed up worst case performance, which, unfortunately, is common. Also several currently unused algorithms in the code (turbo, tophat, etc.) bypass the interpolation code, call get_pixmap directly and so will fail when the pixmap value is NaN. 

I'd punch the author who made this mistake, but unfortunately I'd be punching myself in the face.

**Comment by mcara** [comment]
> ... so that it "thinks" in two dimensions ...

Sounds like applying Cauchy's residue theorem 😄

**Comment by bernie-simon** [comment]
The problem was fixed with the June 21st commit. So I am closing the issue.
