### ISSUE TITLE
TST: Clean up Travis CI matrix

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzle#35]
I think the current Travis CI matrix was copied blindly from an old Astropy project template. It is not optimized for testing this package and needs some serious clean-up.

One example: Cron jobs are defined but it is not actually set up to run in the CI service.

**Comment by jdavies-st** [comment]
Yup, exactly.

**Comment by jdavies-st** [comment]
Fixed in #34, #47 and #54.
