### ISSUE TITLE
Remove all references to INDEF

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzle#40]
Remove references to INDEF from this code.  It is not handled properly anyway.  INDEF has no meaning in C or Python anyway.  It is a holdover from IRAF.  And here, it is set to zero here anyway.  How about we just be explicit?
```
$ grep -r INDEF drizzle | grep -v Binary
drizzle/drizzle.py:                 fillval="INDEF"):
drizzle/drizzle.py:            not overlap it. The default value of INDEF does not set a value.
drizzle/dodrizzle.py:              pixfrac=1.0, kernel='square', fillval="INDEF"):
drizzle/dodrizzle.py:        not overlap it. The default value of INDEF does not set a value.
drizzle/dodrizzle.py:        fillval = 'INDEF'
drizzle/src/cdrizzleapi.c:  char *fillstr = "INDEF";
drizzle/src/cdrizzleapi.c:      strncmp(fillstr, "INDEF", 6) == 0 ||
```
In fact, there shouldn't even be a fill string.  There should be a default value of `0` or `NaN`.  We can argue about which.  😄

**Comment by mcara** [comment]
For backward compatibility, `'INDEF'` will be kept and it has the same meaning as it used to have in the JWST pipeline: when an output image is provided, it does not do anything. That is, basically, it turns off filling.
