### ISSUE TITLE
Add GWCS support to calc_pixmap()

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzle#43]
Currently an implementation of this is in the `jwst` package.

https://github.com/spacetelescope/jwst/blob/bbe04525a7ced5354ed5457798457215bb33d29c/jwst/resample/resample_utils.py#L98-L162

Update both the FITS WCS and GWCS code to use the APE 14 enhancements where possible.

**Comment by mcara** [comment]
fixed via #134
