### ISSUE TITLE
Dimensionality issue when a new plane is added to the context

### ISSUE THREAD

**Issue by RupertDodkins** [spacetelescope/drizzle#50]
There is a dimension mismatch error on line 474 of drizzle.py when there are more than 32 input images. We fixed this by replacing this line with 

self.outcon = np.append(self.outcon, [plane], axis=0)

**Comment by jdavies-st** [comment]
Thanks Rupert.  We'll implement your fix on our end as well and write a test for this.

Sorry for the delayed response.

**Comment by sbs0335** [comment]
First sorry if I am just adding noise here.

This seems to be related to the error I'm finding which is that the add_image (or add_fits_file) method of the Drizzle class will crash if called more than 32 times with the same Drizzle instance. This is a simple test I have made with version 1.13.1 of drizzle.

drizMap = drizzle.drizzle.Drizzle(outwcs=refWcs)

for i in range(32):
    newWcs = refWcs.copy()
    newData = hduList[0].data.copy()
    newData[10*i:10*(i+1),10*i:10*(i+1)] = -40000
    drizMap.add_image(newData,newWcs)
    
drizMap.write('tmp.fits')

produces an image where I can see clearly that all 32 images were coadded (on top of each other as the WCS is always the same). but if I try to do this for I in range(33), it crashes with 

Traceback (most recent call last):

  File "<ipython-input-341-882f7e66d35a>", line 5, in <module>
    drizMap.add_image(newData,newWcs)

  File "/Users/sauvage/opt/anaconda3/lib/python3.8/site-packages/drizzle/drizzle.py", line 372, in add_image
    self.increment_id()

  File "/Users/sauvage/opt/anaconda3/lib/python3.8/site-packages/drizzle/drizzle.py", line 472, in increment_id
    self.outcon = np.append(self.outcon, plane, axis=0)

  File "<__array_function__ internals>", line 5, in append

  File "/Users/sauvage/opt/anaconda3/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4745, in append
    return concatenate((arr, values), axis=axis)

  File "<__array_function__ internals>", line 5, in concatenate

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

**Comment by sbs0335** [comment]
to add to my comment, I think we are talking of the same thing indeed because one way to avoid the crash is to reset the uniqid attribute of the Drizzle instance to 0. It looses the capacity to keep track of which sub image projected where, but it does not crash..

**Comment by jdavies-st** [comment]
No, but thanks for the prod.

We've been busy with some other things here and are finally returning our attention to `drizzle`.  I'll fix this and get a release out asap.

And of course we're always open to pull requests if you find bugs and can fix them.
