### ISSUE TITLE
wt_scl is sometimes a string, sometimes a float

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzle#61]
The interface for wt_scl is not clear.  in `dodrizzle` is described as a float, but everywhere else it is a string.  And sometimes it's an empty string.  This interface needs to be cleaned up and made consistent.

Additionally, within the C code, it is `wtscl`, but the interface presents it as `weight_scale`.

**Comment by mcara** [comment]
Fixed via #134
