### ISSUE TITLE
Set up workflow action to build wheels on different platforms for delivery to PyPI

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzle#62]
See an example here

https://github.com/spacetelescope/synphot_refactor/blob/master/.github/workflows/publish-to-pypi.yml

**Comment by jdavies-st** [comment]
See

https://github.com/pypa/gh-action-pypi-publish

and

https://github.com/pypa/cibuildwheel

**Comment by jdavies-st** [comment]
And

https://github.com/astropy/wheel-forge

**Comment by jdavies-st** [comment]
See examples here

https://github.com/eslavich/drizzle/blob/master/.github/workflows/build.yml

https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

And available `runs-on` platforms here:

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by jdavies-st** [comment]
The scikit-learn folks build wheels nightly:

https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml

**Comment by pllim** [comment]
There are wheels for Linux and OSX now on https://pypi.org/project/drizzle/#files but looks like Windows is omitted. Not sure why.

**Comment by pllim** [comment]
I added wheels for Windows in #128 🤞
