### ISSUE TITLE
"Drizzling" an image into a smaller one does not produce the expected result

### ISSUE THREAD

**Issue by sbs0335** [spacetelescope/drizzle#63]
I am using Drizzle to go back and forth between an astronomical scene (the large image), and a small detector that observe in in scanning mode (building a mosaic of the large scene though an on-the-fly observing mode, and I have discovered that when the image provided to Drizzle.add_image() is larger than that that has been used to create the Drizzle instance, the result is incorrect (empty, or not filled completely, this seems to has a dependence on the image size ratio).

here is a test that I have performed with a fits file that I have created for testing purposes. The image contains a recognisable structure of stripes.

hdu = fits.open('Test_Mire.fits')
sceneWcs = WCS(hdu[0].header)
data = hdu[0].data
plt.imshow(data)

This shows correctly the stripe pattern I expect. 

Now I create a smaller image by extracting the central part and updating the WCS so that its is physically centred on the same sky position

data2 = data[50:-50,50:-50].copy()
tmpWcs = sceneWcs.deepcopy()
tmpWcs.pixel_shape = [3759,3866]
tmpWcs.wcs.crpix = [1929.5-50,1983-50]

Then I use drizzle to add that small image in an drizzled map that is created with the WCS of the larger image

drizMap = Drizzle(outwcs=sceneWcs)
drizMap.add_image(data2,tmpWcs)
plt.imshow(drizMap.outsci)

This shows the expected striped pattern to the exception that there is a band of empty pixels on all 4 sides of the field, as indeed the image that I have drizzled has a smaller coverage.

Then I do the reverse, use the smaller image WCS to create the drizzled map and add the larger image into it.

drizMap = Drizzle(outwcs=tmpWcs)
drizMap.add_image(data,sceneWcs)
plt.imshow(drizMap.outsci)

this image is empty (full of 0s). And the context (outcon[0,:,:]) image is also empty as if, as far as add_image is concerned, they have no geometrical overlap. 

I am not attaching my test image because it is quite large but I've discovered the problem when I was trying to make this with much smaller images (by extracting first a section of the large image, large enough still so that the detector would fit into it whatever the orientation, but still quite smaller that the image I have used for this test example).

This looks like a bug.

Marc

**Comment by sbs0335** [comment]
Out of curiosity I have tried making the drizzle in only a section of the map with the x/y-min/max keyword and this:

drizMap.add_image(data,sceneWcs,xmin=1500,xmax=2500,ymin=1500,ymax=2500)

produced a result that looks more like what is expected but is not quite there because in outsci pixels start to be filled at index 1449 and end being filled at index 2451. So with projection errors>uncertainties that's the right span of values but it is offset. and this offset is maintained if own tries to expand the range of output pixels to fill.

I have tried setting x/y-min to 1 and x/y-max to the number of pixels in these dimensions in the output image (so very close to not using the keywords) and it indeed fills most of the image, though still with an offset. In fact I have made this attempt:

tmpWcs.pixel_shape
Out[589]: (3759, 3866)
drizMap.add_image(data,sceneWcs,xmax=3759,ymax=3866)

where I am setting the x/y max to the actual size of the output image, and the result is an image almost completely filled except that there is a band of 50 pixel left blank at both ends of the field. As if there is an offet between the two wcs. Yet they are a deepcopy of one another, and I have verified that If I use the tmpWcs to get the world coordinate of its crpix (its reference pixel) then use the sceneWcs to get the pixel coordinate of that sky position I end up with the crpix of sceneWcs so they are on top of each other, with tempWcs inside sceneWcs.

Marc

**Comment by sbs0335** [comment]
And finally! 
if I do this:

drizMap.add_image(data,sceneWcs,xmax=3759+50,ymax=3866+50)

i.e. indicating a value for x/y max that is 50 pixels outside the output image, I do get what I expect which is a completely filled output image...

**Comment by sbs0335** [comment]
As I was investigating another weird issue (but found that it was on my side), I really think this error occurs in the c-code. I've followed the whole path of preparing the data up to the c-code call and everything seems to be correct. For instance the pixmap identifies correctly those pixels in the input data (the larger map) that project on the science map (the smaller one). But still the call to tdriz returns that none of the pixels of the input map intercepted the science map.

Unfortunately I don't "read" c and I can't investigate further.

**Comment by jdavies-st** [comment]
Thanks Marc.  This seems like it is essentially the same bug as #41?

**Comment by sbs0335** [comment]
Hi James

Thanks for pointing this out to me. Now that I have looked at issue #41 I think that's exactly that. 

What is puzzling me now that I have read the discussions in #41 and attached issue, is that up to the call to tdriz I think the code is built in the correct way (pls don't take it as a "judgment"! what I mean is that it is able to handle both situations, input wcs smaller than the output wcs, standard use of drizzle, and the reverse which correspond to a situation where we simulate an observation of a large scene, using a small detector).

I read in the discussion suggestions to change how the pixmap is built (by calc_pixmap) but I'm not sure that's the right way to proceed. It's inside the drizzle code that something must be done to include the expectation that the pixmap can contain values that indicate that pixels in the input image fall out of the input image, because as far as computations are concerned there should be no difference.

Actually I think the code was built to expect this unusual situation since it returns the list of lines of the input image that fall out of the output image as well as the list of pixels that fall out (by the way confirming that they ALL fall out of the image, despite the fact that the pixmap locates properly the region where the input image intercepts the output image).

Anyway, sorry for not noticing that this had already been spotted and creating some noise. If I may, do you think there is a chance a correction of this will happen in the near future? I'm asking because I'm unconfortable using a work around and it seems to me that activity on drizzle is low, probably because drizzlepac is the active package now, but I have been unable to identify how I could use drizzlepac for the "simple" actions of drizzle that I am using (and for which it is extremely efficient).

Thanks
