### ISSUE TITLE
Flux increases as ~n^2 when rebinning in x axis by a factor of n 

### ISSUE THREAD

**Issue by Vladan1986** [spacetelescope/drizzle#64]
I am not 100% sure if this is an issue, but when I use drizzle to rebin the 2D image by a factor of n in the x axis the flux increases by  n^2. When I rebin in the y axis the flux is the same. 

Simple example: 
My image is a 8x4 matrix of ones. If I rebin the matrix in the y axis by a factor of 2, I obtain (as expected), a 8x2 matrix of ones.
However, if I take the 8x4 matrix and I rebin in the x axis by a factor of 2, I get a 4x4 matrix of fours.

**Comment by jdavies-st** [comment]
Thanks for the report.  Can  you pass along a code snippet so that we can reproduce?

**Comment by Vladan1986** [comment]
`x_rebin = 2 # rebinning according to the x axis - wavelength
y_rebin = 1 # rebinning according to the y axis slit coord.

flux_arr = np.ones(32).reshape(4, 8)
err_arr = np.ones(32).reshape(4, 8)/100

flux = pyfits.open('test_flux.fits') 
err = pyfits.open('test_err.fits') 
header_out = flux[0].header.copy() # header of the ouptut file = header of the input file
header_out['NAXIS1'] /= x_rebin # rebinning of x axis by a factor of x_rebin
header_out['NAXIS1'] = int(header_out['NAXIS1']) # integer value
header_out['CDELT1'] *= x_rebin # modifying the resolution
header_out['NAXIS2'] /= y_rebin # rebinning of y axis by a factor of y_rebin
header_out['NAXIS2'] = int(header_out['NAXIS2']) # integer
header_out['CDELT2'] *= y_rebin       
wcs_out = wcs.WCS(header_out) # coordinate system of the output file
slit_drz = drizzle.Drizzle(outwcs=wcs_out, pixfrac=1) # Object of the Drizzle class

wht_in  =  1./err_arr**2 # **4 looks smoother! input 2d numpy array containing the pixel by pixel weighting.

# adding the image to the drizzle Object
slit_drz.add_image(flux_arr,in_wcs,inwht= wht_in) 
out_err= 1./slit_drz.outwht**0.5

out_flux = slit_drz.outsci`

**Comment by jdavies-st** [comment]
It's not clear in the snippet what `in_wcs` is here, and that's quite important.

**Comment by Vladan1986** [comment]
wcs is world coordinate system: coordinate system of the image, to map the pixels to frequency.

`with pyfits.open('test_flux.fits', mode='update') as hdul:
    hdr = hdul[0].header
    hdr['NAXIS1'] = (xsize, 'no pixels in x')
    hdr['NAXIS2'] = (ysize, 'no pixels in y')
    hdr['CRPIX1'] = (1, 'x[0] coord')
    hdr['CRPIX2'] = (1, 'y[0] coord')
    hdr['CDELT1'] = (1, 'x resolution')
    hdr['CDELT2'] = (1, 'y resolution')
    in_wcs = wcs.WCS(hdr)`

the output of the in_wcs is:

print(in_wcs)

WCS Keywords

Number of WCS axes: 2
CTYPE : ''  ''  
CRVAL : 0.0  0.0  
CRPIX : 1.0  1.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 1.0  1.0  
NAXIS : 10  4

**Comment by mcara** [comment]
Not enough information to figure out what is going on.
