### ISSUE TITLE
Tests require write access to data directory

### ISSUE THREAD

**Issue by olebole** [spacetelescope/drizzle#8]
Some tests write output files to `DATA_DIR`. If the package is installed system wide, this directory is however readonly for the user, so the tests will fail.

From looking into the code, I would assume that the output files are not needed for the tests at all, but are just there for a later analysis outside of the tests, right? Could writing be switched off by default?

Best regards

Ole

**Comment by bernie-simon** [comment]
> On Nov 10, 2016, at 4:04 AM, Ole Streicher <notifications@github.com> wrote:
> 
> Some tests write output files to DATA_DIR. If the package is installed system wide, this directory is however readonly for the user, so the tests will fail.

If the tests are run the usual way through the “python setup.py test” the tests create a temporaray directory containing the source code. DATA_DIR is defined relative to that directory and the account used to run the tests has write privileges there. I’m not aware of any problems running tests as root. If you have had any problems, please send me the output of the setup command and I will invrstigate them. 

> From looking into the code, I would assume that the output files are not needed for the tests at all, but are just there for a later analysis outside of the tests, right? Could writing be switched off by default?

The input files for the tests are also located in DATA_DIR. They are copied there at test startup. You can’t make DATA_DIR optional without rewriting all the tests.

**Comment by olebole** [comment]
I want to run the tests in two cases: First, during the package build, to ensure that the package is built correctly. Debian runs on a lot of CPUs, and I don't want to create a non-working package on any of them.
Second, I want to run it within our [Continuous Integration framework](https://ci.debian.net/). This runs the test on the *installed* package each time a dependency (for example numpy) changes. This will make sure that the package keeps in a good state. Numpy [caused some problems in the past when updated](https://github.com/astropy/astropy/issues/4548), so it definitely worth doing so.
Therefore the tests should not modify the test data (so that I can still use them to install after I did the build time test). The CI test is run as an ordinary user, so it cannot change the installed package.
I am going to patch the tests subdir for this and will provide a pull request here; this is just for the rationale.
