### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [spacetelescope/drizzle#90]
Would you like to add more error handling for return values from functions like the following?
* [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [log_name](https://github.com/spacetelescope/drizzle/blob/80296bb7f3465901a50e0fff93af8dec1cf241c2/src/tests/pandokia_fct.h#L65)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [setup_parameters](https://github.com/spacetelescope/drizzle/blob/80296bb7f3465901a50e0fff93af8dec1cf241c2/src/tests/utest_cdrizzle.c#L249)

**Comment by mcara** [comment]
No

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
